### ISSUE TITLE
option -c to include at least one capital letter fails

### ISSUE THREAD

**Issue by deusmax** [tytso/pwgen#5]
I noticed the option -c (--capitalize) is not always honored in the output. 

Here is as sample output:

> pwgen -B --capitalize -y -n 10 20
> Et&eeL3iet juPh+ie9Fu xoo%Piepi3 zo7vey*u7M bee"thah4o Nie7oothe^ peeb]i7fah
> kaew7Jiz`u Uw+ee9naix Aito#Yie4a uphu;sa4La va4Cae:the hob~ai9Thu wiePae9Hu:
> ohm;oh9dee Egae\F4iet Phee`th3oe cie4wieJe( ueg7Pic-oh um4ciodi:e

in this run, 4 results do not have a capital letter.

This  is frequently seen, almost every time.
My setup is: Debian Linux 10 (buster)
pwgen version: 2.08-1

**Comment by stefanct** [comment]
This has been fixed in https://github.com/tytso/pwgen/commit/54d6c1c0e8c380583c7b3f87c0ff19146232a771
